export const CHALLENGE_BANK = [
  // First 100 challenges
  { title: 'Your Morning Coffee', description: 'Draw your coffee mug, the steam rising, or what your coffee makes you feel like.' },
  { title: 'Tiny Creatures', description: 'Invent a bug, fairy, or mini monster.' },
  { title: 'Inside Your Bag', description: 'Sketch what\'s in your purse, backpack, or dream travel bag.' },
  { title: 'Rainy Day Vibes', description: 'Umbrellas, puddles, clouds, or cozy indoor scenes.' },
  { title: 'Doodle Your Mood', description: 'Use shapes, lines, or faces to express how you feel.' },
  { title: 'Magic Potions', description: 'Design bottles, labels, ingredients, and effects!' },
  { title: 'Your Favorite Snack', description: 'Sweet, salty, savory—make it cute or realistic.' },
  { title: 'Musical Shapes', description: 'What would music look like if it were a doodle?' },
  { title: 'Silly Robots', description: 'Create a funny or helpful robot with odd features.' },
  { title: 'Houseplants With Personality', description: 'Give each plant a name, face, and mood.' },
  { title: 'What\'s in the Sky?', description: 'Sun, stars, UFOs, hot air balloons—let your mind float.' },
  { title: 'Your Dream Shoes', description: 'Design sneakers, boots, or fantasy footwear.' },
  { title: 'Letters With Attitude', description: 'Make each letter of your name have its own style.' },
  { title: 'Under the Sea', description: 'Fish, coral, treasure, submarines—go deep.' },
  { title: 'The Perfect Picnic', description: 'Blankets, food, ants… or maybe a twist?' },
  { title: 'Self-Portrait as a Doodle', description: 'Draw yourself in your doodle style!' },
  { title: 'Doodle a Sound', description: 'What does laughter, wind, or traffic look like?' },
  { title: 'City in the Clouds', description: 'Floating buildings, bridges in the sky, dreamy skylines.' },
  { title: 'Your Favorite Word', description: 'Illustrate it in a creative way—with images, patterns, or color.' },
  { title: 'A Scene from Your Day', description: 'Pick a small moment and doodle it: breakfast, a walk, a nap.' },
  { title: 'Cozy Corner', description: 'Draw your favorite reading spot or relaxing place.' },
  { title: 'Breakfast Champion', description: 'Draw your favorite morning meal—pancakes, cereal, toast!' },
  { title: 'Pocket Buddy', description: 'Design a tiny creature that lives in your pocket.' },
  { title: 'Garden Friends', description: 'Draw butterflies, bees, ladybugs, or garden visitors.' },
  { title: 'My Pet (Real or Fantasy)', description: 'Draw your pet, a pet you wish you had, or a made-up creature.' },
  { title: 'Cloud Shapes', description: 'What do you see in the clouds today?' },
  { title: 'Pattern Party', description: 'Create a repeating pattern with your favorite things.' },
  { title: 'Silly Hats', description: 'Design the most ridiculous or wonderful hat you can imagine.' },
  { title: 'Food Friends', description: 'Give your favorite food a face and personality.' },
  { title: 'Window View', description: 'Draw what you see (or wish you saw) from a window.' },
  { title: 'Retro Vibes', description: 'Draw something inspired by the 70s, 80s, or 90s.' },
  { title: 'Monster Under the Bed', description: 'Design a friendly (or scary!) monster.' },
  { title: 'Transportation Dreams', description: 'Draw fantastical bikes, cars, or vehicles.' },
  { title: 'Book Cover', description: 'Design a cover for your favorite book or your life.' },
  { title: 'Meme Me', description: 'Turn yourself or your pet into a meme.' },
  { title: 'Space Explorer', description: 'Astronauts, aliens, rockets, or distant planets.' },
  { title: 'Rainbow Mood', description: 'Use rainbow colors to show your feelings.' },
  { title: 'My Hero', description: 'Draw your personal hero—real or fictional.' },
  { title: 'Tiny Kitchen', description: 'Draw a miniature kitchen with tiny cooking scenes.' },
  { title: 'Dance Move', description: 'Illustrate your favorite dance move or pose.' },
  { title: 'Weather Magic', description: 'Draw what weather would look like if it had power.' },
  { title: 'Sweet Treats', description: 'Donuts, cakes, ice cream—draw your favorites!' },
  { title: 'Dream Pet', description: 'Design an animal that doesn\'t exist in real life.' },
  { title: 'Hobby Time', description: 'Draw yourself doing your favorite hobby.' },
  { title: 'Mysterious Map', description: 'Create a map of an imaginary place.' },
  { title: 'Face Swap', description: 'Give yourself animal features or mix two faces.' },
  { title: 'Starry Night', description: 'Draw a dreamy night sky with your own constellations.' },
  { title: 'Transportation Collage', description: 'Mix cars, trains, planes, and boats into one scene.' },
  { title: 'Lazy Afternoon', description: 'What do you like to do when you\'re being lazy?' },
  { title: 'Festival Fun', description: 'Draw a celebration—birthday, festival, or party scene.' },
  { title: 'Animal Kingdom', description: 'Draw animals having a meeting or party.' },
  { title: 'My Room', description: 'Sketch your bedroom or dream room.' },
  { title: 'Story Scene', description: 'Illustrate a scene from a book, movie, or your own story.' },
  { title: 'Outer Space', description: 'Planets, galaxies, astronauts, or space creatures.' },
  { title: 'Chonky Animals', description: 'Draw your favorite animals in cute, chunky style.' },
  { title: 'Flower Power', description: 'Design magical flowers with patterns and colors.' },
  { title: 'Game Character', description: 'Draw a character from your favorite game.' },
  { title: 'Morning Routine', description: 'Illustrate your typical morning step by step.' },
  { title: 'Spooky Season', description: 'Pumpkins, ghosts, or other spooky fun!' },
  { title: 'Friends Forever', description: 'Draw you and your best friend(s).' },
  { title: 'Ice Cream Truck', description: 'Design your dream ice cream truck or flavor.' },
  { title: 'Coat of Arms', description: 'Create a personal crest with your symbols.' },
  { title: 'Dinosaur World', description: 'Draw dinosaurs doing everyday human activities.' },
  { title: 'Neighborhood', description: 'Sketch your street, neighbors, or dream neighborhood.' },
  { title: 'Weather Report', description: 'Draw a weather forecast for an imaginary place.' },
  { title: 'Superpower', description: 'If you had one superpower, what would it look like?' },
  { title: 'Breakfast Around World', description: 'Draw breakfast foods from different cultures.' },
  { title: 'Cloud Home', description: 'Design a house that floats on clouds.' },
  { title: 'Music Notes', description: 'Make musical notes come alive in a doodle.' },
  { title: 'Pirate Adventure', description: 'Treasure maps, ships, or pirate crew.' },
  { title: 'Pet Day', description: 'Draw your pet doing human activities.' },
  { title: 'Time Machine', description: 'Design a vehicle that travels through time.' },
  { title: 'Silly Sandwich', description: 'Design the most absurd sandwich ever.' },
  { title: 'Jungle Safari', description: 'Lions, tigers, or exotic animals in the wild.' },
  { title: 'My Family', description: 'Draw your family as cute characters.' },
  { title: 'Dream Vacation', description: 'Where would you go? Draw it!' },
  { title: 'Magic Wand', description: 'Design a wand with specific powers.' },
  { title: 'Snow Day', description: 'Sledding, snowmen, or cozy winter scenes.' },
  { title: 'Robot Friend', description: 'Draw a friendly robot companion.' },
  { title: 'Fruit Faces', description: 'Give fruits or vegetables personalities.' },
  { title: 'Candy Land', description: 'Design a world made entirely of candy.' },
  { title: 'Talent Show', description: 'Draw someone performing their special talent.' },
  { title: 'Haunted House', description: 'Draw a spooky or funny haunted house.' },
  { title: 'Unicorn Paradise', description: 'Rainbows, glitter, and unicorn magic!' },
  { title: 'Ocean Friends', description: 'Dolphins, whales, or sea turtles having fun.' },
  { title: 'Treehouse Hideout', description: 'Design the ultimate treehouse.' },
  { title: 'Sleepy Creatures', description: 'Draw animals sleeping in funny positions.' },
  { title: 'My Hobbies', description: 'Illustrate all your hobbies in one scene.' },
  { title: 'Circus Time', description: 'Acrobats, clowns, or carnival fun!' },
  { title: 'Dragon Tales', description: 'Design a friendly dragon and its world.' },
  { title: 'Bff Bracelet', description: 'Draw friendship bracelets with symbols.' },
  { title: 'Park Adventure', description: 'Swings, slides, and playground fun.' },
  { title: 'Mushroom Village', description: 'Design a tiny village made of mushrooms.' },
  { title: 'Vacation Postcard', description: 'Create a postcard from dream vacation.' },
  { title: 'Robot Pet', description: 'Design a mechanical pet with cool features.' },

  // 101-200
  { title: 'Rainbow Bridge', description: 'Draw a colorful bridge connecting two worlds.' },
  { title: 'Sleepy Sloth', description: 'A sloth hanging from a branch doing absolutely nothing.' },
  { title: 'Bubble Bath', description: 'Draw a character enjoying a luxurious bubble bath.' },
  { title: 'Autumn Leaves', description: 'Fallen leaves in all the autumn colors.' },
  { title: 'Winter Wonderland', description: 'A snowy scene with snowflakes and icicles.' },
  { title: 'Spring Blooms', description: 'Flowers blooming after a long winter.' },
  { title: 'Summer Beach', description: 'Sun, sand, waves, and beach vibes.' },
  { title: 'Cottage Core', description: 'A cozy cottage surrounded by nature.' },
  { title: 'Midnight Snack', description: 'What you eat when no one is watching.' },
  { title: 'Garden Gnome', description: 'Design your own garden gnome character.' },
  { title: 'Fairy Tale Ending', description: 'Redraw the ending of your favorite fairy tale.' },
  { title: 'Tea Party', description: 'Have tea with imaginary friends.' },
  { title: 'Stargazing', description: 'Lie on the grass and watch the stars.' },
  { title: 'Rainbow after Rain', description: 'That magical moment when the sun appears.' },
  { title: 'Cozy Sweater', description: 'Design the coziest sweater ever.' },
  { title: 'Secret Garden', description: 'A hidden garden with magical elements.' },
  { title: 'Hot Cocoa', description: 'The perfect cup of hot chocolate.' },
  { title: 'Lighthouse Keeper', description: 'A lighthouse on a stormy night.' },
  { title: 'Paper Boat', description: 'A small boat sailing in a puddle.' },
  { title: 'Moonlight Serenade', description: 'A moonlit scene with musical elements.' },
  { title: 'Baking Day', description: 'Flour, dough, and sweet treats.' },
  { title: 'Pajama Day', description: 'Staying in pajamas all day long.' },
  { title: 'Rainy Window', description: 'Looking out a rainy window with a warm drink.' },
  { title: 'Cozy Fireplace', description: 'A warm fire on a cold night.' },
  { title: 'Reading Nook', description: 'The perfect spot for reading books.' },
  { title: 'Hot Air Balloon', description: 'Floating over colorful landscapes.' },
  { title: 'Camping Night', description: 'A tent under the stars.' },
  { title: 'Picnic Blanket', description: 'A checkered blanket with delicious food.' },
  { title: 'Birdwatching', description: 'Observing birds in their natural habitat.' },
  { title: 'Butterfly Garden', description: 'Colorful butterflies among flowers.' },
  { title: 'Mountain Peak', description: 'The view from the top of a mountain.' },
  { title: 'Desert Oasis', description: 'A palm tree surrounded by sand.' },
  { title: 'Tropical Island', description: 'Sunset over a tropical paradise.' },
  { title: 'Northern Lights', description: 'The magical aurora borealis.' },
  { title: 'Waterfall Wonder', description: 'A majestic waterfall with a rainbow.' },
  { title: 'Enchanted Forest', description: 'A magical forest with glowing elements.' },
  { title: 'Crystal Cave', description: 'A cave filled with glittering crystals.' },
  { title: 'Sunset Boulevard', description: 'A beautiful sunset over the city.' },
  { title: 'Starry Tent', description: 'A tent with stars visible through the fabric.' },
  { title: 'Morning Dew', description: 'Drops of water on spider webs.' },
  { title: 'Snowflake Magic', description: 'Each snowflake is unique and beautiful.' },
  { title: 'Pineapple Smile', description: 'A happy pineapple with a tropical vibe.' },
  { title: 'Watermelon Summer', description: 'A slice of watermelon on a summer day.' },
  { title: 'Lemonade Stand', description: 'A colorful stand selling lemonade.' },
  { title: 'Berry Picking', description: 'Collecting berries in a basket.' },
  { title: 'Apple Orchard', description: 'Rows of apple trees in autumn.' },
  { title: 'Honeycomb Pattern', description: 'A hexagonal pattern like a beehive.' },
  { title: 'Sunflower Field', description: 'Tall sunflowers facing the sun.' },
  { title: 'Tulip Garden', description: 'A rainbow of colorful tulips.' },
  { title: 'Cactus Friend', description: 'A cute cactus with a smiley face.' },
  { title: 'Bamboo Grove', description: 'Tall bamboo creating natural walls.' },
  { title: 'Maple Syrup', description: 'A maple leaf with dripping syrup.' },
  { title: 'Acorn Collection', description: 'Tiny acorns with tiny hats.' },
  { title: 'Feather Friends', description: 'Colorful feathers from exotic birds.' },
  { title: 'Shell Collection', description: 'Seashells arranged on the beach.' },
  { title: 'Coral Reef', description: 'Underwater colorful coral formations.' },
  { title: 'Jellyfish Dance', description: 'Glowing jellyfish floating in the ocean.' },
  { title: 'Sea Turtle Journey', description: 'A sea turtle swimming through the sea.' },
  { title: 'Crab\'s Home', description: 'A hermit crab finding a new shell.' },
  { title: 'Octopus Garden', description: 'An octopus tending an underwater garden.' },
  { title: 'Starfish Shore', description: 'A starfish resting on a rock.' },
  { title: 'Seahorse Dad', description: 'A male seahorse carrying babies.' },
  { title: 'Whale Song', description: 'A whale singing in the deep ocean.' },
  { title: 'Dolphin Play', description: 'Dolphins jumping and playing.' },
  { title: 'Shark Guardian', description: 'A friendly shark protecting smaller fish.' },
  { title: 'Mermaid\'s Cove', description: 'A hidden cove where a mermaid lives.' },
  { title: 'Pirate Treasure', description: 'A chest full of gold and jewels.' },
  { title: 'Shipwreck Discovery', description: 'An old shipwreck explored by divers.' },
  { title: 'Mermaid Tail', description: 'Shimmering scales of a mermaid tail.' },
  { title: 'Tropical Fish', description: 'Brightly colored fish in coral.' },
  { title: 'Lobster\'s Claw', description: 'A big lobster showing off its claws.' },
  { title: 'Pearl Inside', description: 'An oyster with a glowing pearl.' },
  { title: 'Wave Rider', description: 'A surfer riding a big wave.' },
  { title: 'Beach Sunset', description: 'The sun setting over the ocean.' },
  { title: 'Sailboat Race', description: 'Small sailboats competing on the water.' },
  { title: 'Fishing Day', description: 'Catching fish on a quiet lake.' },
  { title: 'River Stones', description: 'Smooth stones in a babbling brook.' },
  { title: 'Water Splash', description: 'Kids splashing in a puddle or pool.' },
  { title: 'Ice Skating', description: 'Someone gracefully ice skating.' },
  { title: 'Snowball Fight', description: 'A fun snow day with friends.' },
  { title: 'Igloo Home', description: 'An Eskimo-style snow shelter.' },
  { title: 'Sledding Hill', description: 'Racing down a snowy hill on a sled.' },
  { title: 'Frozen Lake', description: 'Fish swimming under frozen water.' },
  { title: 'Penguin Colony', description: 'A group of penguins on an iceberg.' },
  { title: 'Polar Bear Rest', description: 'A polar bear on an ice flow.' },
  { title: 'Arctic Fox', description: 'A white fox blending in the snow.' },
  { title: 'Snowy Owl', description: 'A wise owl in a snowy forest.' },
  { title: 'Ice Cream Cone', description: 'The most beautiful ice cream cone.' },
  { title: 'Cotton Candy', description: 'Pink and blue cotton candy clouds.' },
  { title: 'Popcorn Bucket', description: 'A bucket overflowing with popcorn.' },
  { title: 'Movie Night', description: 'Cozy setup for watching movies.' },
  { title: 'Gaming Setup', description: 'The ultimate gaming station.' },
  { title: 'Art Corner', description: 'A creative space for making art.' },
  { title: 'Music Room', description: 'Instruments and musical vibes.' },
  { title: 'Plant Shelf', description: 'A shelf full of happy plants.' },

  // 201-300
  { title: 'Desk Organization', description: 'A beautifully organized desk setup.' },
  { title: 'Bullet Journal', description: 'A decorated planner page.' },
  { title: 'Recipe Card', description: 'A handwritten recipe with doodles.' },
  { title: 'Travel Journal', description: 'Pages from a travel diary.' },
  { title: 'Vision Board', description: 'A collage of dreams and goals.' },
  { title: 'Gratitude List', description: 'Things you are thankful for.' },
  { title: 'Daily Routine', description: 'Your perfect day visualized.' },
  { title: 'Mood Tracker', description: 'Tracking emotions with colors.' },
  { title: 'Habit Tracker', description: 'Checking off daily habits.' },
  { title: 'Goal Setting', description: 'Steps to achieve your dreams.' },
  { title: 'Self Care', description: 'Activities that make you happy.' },
  { title: 'Worry Monster', description: 'A cute monster eating your worries.' },
  { title: 'Breathing Space', description: 'A calming breathing exercise visual.' },
  { title: 'Happy Place', description: 'Draw your mental happy place.' },
  { title: 'Emotion Wheel', description: 'All the feelings you can name.' },
  { title: 'Safe Space', description: 'A place where you feel completely safe.' },
  { title: 'Growth Mindset', description: 'Challenges becoming opportunities.' },
  { title: 'Kindness Rocks', description: 'Painted rocks with kind messages.' },
  { title: 'Friendship Bracelet', description: 'Woven threads of friendship.' },
  { title: 'Love Letter', description: 'A romantic letter with doodles.' },
  { title: 'Birthday Card', description: 'A handmade birthday greeting.' },
  { title: 'Thank You Note', description: 'Expressing gratitude creatively.' },
  { title: 'Apology Accepted', description: 'A reconciliation scene.' },
  { title: 'Encouragement', description: 'Words that lift someone up.' },
  { title: 'Congratulations', description: 'A celebration of achievement.' },
  { title: 'Good Morning', description: 'The start of a beautiful day.' },
  { title: 'Good Night', description: 'Sweet dreams and peaceful sleep.' },
  { title: 'Welcome Home', description: 'The comfort of being home.' },
  { title: 'Bonfire Night', description: 'Warmth and light from flames.' },
  { title: 'Campfire Stories', description: 'Ghost stories under the stars.' },
  { title: 'Night Sky Stories', description: 'Connecting stars into pictures.' },
  { title: 'Moon Phases', description: 'The moon in all its stages.' },
  { title: 'Solar System', description: 'Planets orbiting the sun.' },
  { title: 'Rocket Launch', description: 'Blastoff into space!' },
  { title: 'Space Station', description: 'Humans living in space.' },
  { title: 'Alien Friend', description: 'A friendly alien visiting Earth.' },
  { title: 'UFO Sighting', description: 'A mysterious flying saucer.' },
  { title: 'Moon Base', description: 'Future life on the moon.' },
  { title: 'Mars Colony', description: 'Humans settling on Mars.' },
  { title: 'Comet Tail', description: 'A streaking comet across the sky.' },
  { title: 'Shooting Star', description: 'Make a wish on a falling star.' },
  { title: 'Constellation Art', description: 'Drawing pictures with stars.' },
  { title: 'Galaxy Swirl', description: 'A spiral galaxy with billions of stars.' },
  { title: 'Black Hole', description: 'The mysterious space phenomenon.' },
  { title: 'Astronaut Helmet', description: 'A reflection in an astronaut visor.' },
  { title: 'Space Suit', description: 'The gear that keeps astronauts alive.' },
  { title: 'Saturn\'s Rings', description: 'The beautiful rings of Saturn.' },
  { title: 'Jupiter\'s Storm', description: 'The Great Red Spot of Jupiter.' },
  { title: 'Venus Clouds', description: 'Swirling clouds of Venus.' },
  { title: 'Mercury Craters', description: 'The cratered surface of Mercury.' },
  { title: 'Neptune Winds', description: 'The fastest winds in the solar system.' },
  { title: 'Pluto Heart', description: 'The iconic heart of Pluto.' },
  { title: 'Earth from Space', description: 'Our beautiful blue planet.' },
  { title: 'Moon Landing', description: 'The historic Apollo 11 moment.' },
  { title: 'Space Shuttle', description: 'The reusable spacecraft.' },
  { title: 'ISS Flyover', description: 'The International Space Station overhead.' },
  { title: 'Space Walk', description: 'An astronaut floating in space.' },
  { title: 'Zero Gravity', description: 'Things floating in space.' },
  { title: 'Space Food', description: 'What astronauts eat in space.' },
  { title: 'Alien Landscape', description: 'An alien planet with two suns.' },
  { title: 'Spaceship Interior', description: 'The cockpit of a spaceship.' },
  { title: 'Cosmic Dust', description: 'The building blocks of stars.' },
  { title: 'Nebula Colors', description: 'Clouds of gas and dust in space.' },
  { title: 'Star Nursery', description: 'Where new stars are born.' },
  { title: 'Supernova Explosion', description: 'The death of a massive star.' },
  { title: 'Meteor Shower', description: 'Shooting stars lighting up the night.' },
  { title: 'Asteroid Belt', description: 'Rocks orbiting between Mars and Jupiter.' },
  { title: 'Moon Crater', description: 'The surface of the moon up close.' },
  { title: 'Space Volcano', description: 'Volcanoes on other worlds.' },
  { title: 'Crystal Planet', description: 'A planet made entirely of crystals.' },
  { title: 'Ocean Planet', description: 'A planet covered in deep water.' },
  { title: 'Desert Planet', description: 'Endless sand dunes under twin suns.' },
  { title: 'Ice Planet', description: 'A frozen world with glowing auroras.' },
  { title: 'Lava World', description: 'A planet with rivers of fire.' },
  { title: 'Cloud City', description: 'A city floating in the atmosphere.' },
  { title: 'Tree City', description: 'A city built into giant trees.' },
  { title: 'Underground City', description: 'Life beneath the surface.' },
  { title: 'Sky Islands', description: 'Floating islands in the sky.' },
  { title: 'Underwater Base', description: 'A research station under the sea.' },
  { title: 'Desert Oasis City', description: 'A lush city in the desert.' },
  { title: 'Mountain Fortress', description: 'A castle on a mountain peak.' },
  { title: 'Floating Market', description: 'Boats selling goods on water.' },
  { title: 'Night Market', description: 'Stalls lit up at night.' },
  { title: 'Food Truck', description: 'A colorful food truck design.' },
  { title: 'Coffee Shop', description: 'The coziest coffee shop interior.' },
  { title: 'Bookstore Corner', description: 'A quiet corner in a bookstore.' },
  { title: 'Library Ladder', description: 'Reaching for books on high shelves.' },
  { title: 'Arcade Game', description: 'Classic arcade machine with bright lights.' },
  { title: 'Bowling Night', description: 'Fun at the bowling alley.' },
  { title: 'Mini Golf', description: 'A whimsical mini golf hole.' },
  { title: 'Escape Room', description: 'Clues and puzzles everywhere.' },
  { title: 'Karaoke Night', description: 'Singing your heart out.' },
  { title: 'Dance Party', description: 'Lights and music and dancing.' },
  { title: 'Concert Crowd', description: 'Favorite band playing live.' },
  { title: 'Festival Costumes', description: 'People in creative costumes.' },
  { title: 'Parade Float', description: 'A colorful parade float design.' },
  { title: 'Fireworks Show', description: 'Sparkles and bursts in the sky.' },

  // 301-400
  { title: 'Lantern Festival', description: 'Floating lanterns lighting up the night.' },
  { title: 'Diya Lamp', description: 'Decorated oil lamps for Diwali.' },
  { title: 'Lanterns of Love', description: 'Paper lanterns with wishes.' },
  { title: 'Confetti Celebration', description: 'Throwing confetti in the air.' },
  { title: 'Balloon Animal', description: 'Twisted balloon creations.' },
  { title: 'Magic Show', description: 'A magician pulling rabbits from hats.' },
  { title: 'Juggling Act', description: 'Someone juggling colorful balls.' },
  { title: 'Face Painting', description: 'Art transforming faces.' },
  { title: 'Bubble Show', description: 'Giant soap bubbles floating away.' },
  { title: 'Balloon Pop', description: 'Popping balloons at a party.' },
  { title: 'Cake Decorating', description: 'A beautifully decorated cake.' },
  { title: 'Cupcake Toppings', description: 'Cupcakes with all the toppings.' },
  { title: 'Cookie Decorating', description: 'Sugar cookies with frosting.' },
  { title: 'Pizza Making', description: 'Stretching dough and adding toppings.' },
  { title: 'Sushi Art', description: 'Colorful sushi arranged beautifully.' },
  { title: 'Fruit Carving', description: 'Fruit shaped like flowers.' },
  { title: 'Vegetable Garden', description: 'Growing your own vegetables.' },
  { title: 'Herb Pot', description: 'A pot of fresh herbs on a windowsill.' },
  { title: 'Succulent Collection', description: 'Cute small succulents in pots.' },
  { title: 'Terrarium World', description: 'A tiny ecosystem in a jar.' },
  { title: 'Bonsai Tree', description: 'A miniature tree carefully shaped.' },
  { title: 'Flower Arrangement', description: 'Beautiful flowers in a vase.' },
  { title: 'Wreath Making', description: 'A decorative wreath for any season.' },
  { title: 'Ribbon Art', description: 'Creating with colorful ribbons.' },
  { title: 'Tie Dye Pattern', description: 'Swirls of vibrant colors.' },
  { title: 'Macramé Hanger', description: 'Knotted rope holding a plant.' },
  { title: 'Cross Stitch', description: 'X marks forming a pattern.' },
  { title: 'Embroidery Hoop', description: 'Fabric stretched in an embroidery hoop.' },
  { title: 'Knitting needles', description: 'Yarn and knitting needles.' },
  { title: 'Crochet Project', description: 'A half-finished crochet piece.' },
  { title: 'Quilting Pattern', description: 'Pieces of fabric sewn together.' },
  { title: 'Sewing Kit', description: 'Needles, thread, and buttons.' },
  { title: 'Origami Crane', description: 'A delicate folded paper crane.' },
  { title: 'Paper Airplane', description: 'The perfect flying paper plane.' },
  { title: 'Gift Wrapping', description: 'Beautifully wrapped presents.' },
  { title: 'Gift Box', description: 'A surprise inside a box.' },
  { title: 'Handwritten Letter', description: 'A personal letter with decorations.' },
  { title: 'Envelope Design', description: 'Decorated envelope with wax seal.' },
  { title: 'Postcard Collection', description: 'Vintage postcards from travels.' },
  { title: 'Stamp Collection', description: 'Rare stamps from around the world.' },
  { title: 'Coin Collector', description: 'Old coins with historical designs.' },
  { title: 'Fossil Hunt', description: 'Finding ancient treasures in rocks.' },
  { title: 'Rock Painting', description: 'Painted rocks hiding for others.' },
  { title: 'Pressed Flowers', description: 'Flowers preserved between pages.' },
  { title: 'Leaf Art', description: 'Leaves arranged into pictures.' },
  { title: 'Pinecone Collection', description: 'Pinecones of all shapes and sizes.' },
  { title: 'Feather Collection', description: 'Beautiful feathers found outdoors.' },
  { title: 'Shell Art', description: 'Shells arranged into art.' },
  { title: 'Driftwood Sculpture', description: 'Wood shaped by the sea.' },
  { title: 'Sand Castle', description: 'An elaborate sand structure.' },
  { title: 'Snow Sculpture', description: 'Ice carved into shapes.' },
  { title: 'Ice Sculpture', description: 'A melting ice art piece.' },
  { title: 'Pumpkin Carving', description: 'Jack-o-lantern faces for Halloween.' },
  { title: 'Cardboard Fort', description: 'A fortress made of boxes.' },
  { title: 'Pillow Den', description: 'A cozy den made of pillows.' },
  { title: 'Blanket Fort', description: 'A secret hideout under blankets.' },
  { title: 'Treasure Map', description: 'An old map with an X marking the spot.' },
  { title: 'Magic Potion', description: 'Glowing liquid in a bottle.' },
  { title: 'Spell Book', description: 'A mysterious book of magic.' },
  { title: 'Crystal Ball', description: 'Gazing into the future.' },
  { title: 'Fortune Teller', description: 'A mystical fortune telling scene.' },
  { title: 'Fairy Door', description: 'A tiny door for forest fairies.' },
  { title: 'Gnome Home', description: 'A cozy gnome village.' },
  { title: 'Elf Workshop', description: 'Where elves make toys.' },
  { title: 'Santa\'s Sleigh', description: 'Flying through the night sky.' },
  { title: 'Reindeer Friends', description: 'Rudolph and friends.' },
  { title: 'Snowman Family', description: 'Three snowmen of different sizes.' },
  { title: 'Penguin Parade', description: 'Waddle waddle across the ice.' },
  { title: 'Polar Express', description: 'A train through snowy mountains.' },
  { title: 'Gingerbread House', description: 'A candy-covered cottage.' },
  { title: 'Candy Cane Lane', description: 'Houses decorated for the holidays.' },
  { title: 'Ornament Collection', description: 'Sparkly decorations for the tree.' },
  { title: 'Wreath of Memories', description: 'A wreath with photos and decorations.' },
  { title: 'Mistletoe Kiss', description: 'Couples under the mistletoe.' },
  { title: 'New Year Countdown', description: 'Celebrating midnight.' },
  { title: 'Fireplace Stocking', description: 'Stockings hung by the fire.' },
  { title: 'Cozy Mittens', description: 'Warm mittens with patterns.' },
  { title: 'Knit Scarf', description: 'A long colorful scarf.' },
  { title: 'Wool Hat', description: 'A warm hat for cold days.' },
  { title: 'Fuzzy Slippers', description: 'The comfiest slippers ever.' },
  { title: 'Hot Water Bottle', description: 'A cozy warmth source.' },
  { title: 'Electric Blanket', description: 'Warmth at the touch of a button.' },
  { title: 'Radiator Friends', description: 'Things drying on a warm radiator.' },
  { title: 'Scented Candle', description: 'A flickering candle with warm vibes.' },
  { title: 'Essential Oils', description: 'Little bottles of nature\'s scents.' },
  { title: 'Bath Bomb Fizz', description: 'Colorful fizzing in the tub.' },
  { title: 'Face Mask', description: 'A relaxing spa face mask.' },
  { title: 'Manicure Time', description: 'Colorful nail polish designs.' },
  { title: 'Spa Day', description: 'Relaxation and pampering.' },
  { title: 'Meditation Corner', description: 'A peaceful spot for mindfulness.' },
  { title: 'Yoga Pose', description: 'A tree pose or warrior stance.' },
  { title: 'Tai Chi Flow', description: 'Slow, graceful movements.' },
  { title: 'Morning Stretch', description: 'Waking up the body gently.' },
  { title: 'Dancingalone', description: 'Dancing in your room alone.' },
  { title: 'Sing in the Shower', description: 'Water and music together.' },
  { title: 'Bath Time Relaxation', description: 'Soaking in a warm bath.' },
  { title: 'Nap Time', description: 'The best afternoon snooze.' },
  { title: 'Cloud Watching', description: 'Finding shapes in the clouds.' },

  // 401-500
  { title: 'Sunset Gazing', description: 'Watching the day turn to night.' },
  { title: 'Sunrise Promise', description: 'A new day full of possibilities.' },
  { title: 'Picnic Blanket Roll', description: 'Rolling up the picnic blanket.' },
  { title: 'Hammock Nap', description: 'Swaying gently in a hammock.' },
  { title: 'Porch Swing', description: 'Rocking back and forth on a porch.' },
  { title: 'Balcony Garden', description: 'Small space, big greenery.' },
  { title: 'Rooftop View', description: 'The city from above.' },
  { title: 'Window Sill Plants', description: 'Little green friends on the sill.' },
  { title: 'Kitchen Herbs', description: 'Fresh basil, mint, and more.' },
  { title: 'Fruit Bowl', description: 'Apples, oranges, and bananas.' },
  { title: 'Breakfast in Bed', description: 'Tray with coffee and toast.' },
  { title: 'Dining Table', description: 'A family dinner setting.' },
  { title: 'Cereal Bowl', description: 'The most important meal start.' },
  { title: 'Sandwich Quarter', description: 'A cut sandwich into triangles.' },
  { title: 'Soup Bowl', description: 'Warm soup in a cozy bowl.' },
  { title: 'Salad Bowl', description: 'Fresh greens and colorful veggies.' },
  { title: 'Pasta Plate', description: 'Twirly noodles on a plate.' },
  { title: 'Rice Bowl', description: 'A bowl of fluffy rice with toppings.' },
  { title: 'Taco Tuesday', description: 'Tacos with all the fixings.' },
  { title: 'Sushi Plate', description: 'Beautiful sushi arrangements.' },
  { title: 'Burrito Wrap', description: 'A stuffed tortilla ready to eat.' },
  { title: 'Pizza Slice', description: 'A perfect triangle of pizza.' },
  { title: 'Birthday Cake', description: 'Candles lit on a celebration cake.' },
  { title: 'Graduation Cap', description: 'Tossing the cap in the air.' },
  { title: 'First Driver License', description: 'That exciting photo ID.' },
  { title: 'First Apartment', description: 'Empty rooms waiting to be filled.' },
  { title: 'Housewarming Gift', description: 'Bringing something for the new home.' },
  { title: 'Moving Day', description: 'Boxes stacked and ready.' },
  { title: 'New Job First Day', description: 'Nervous and excited vibes.' },
  { title: 'Promotion Celebration', description: 'You did it!' },
  { title: 'Retirement Party', description: 'End of one chapter, start of another.' },
  { title: 'Wedding Day', description: 'The happiest day of two people.' },
  { title: 'Anniversary Dinner', description: 'Celebrating love together.' },
  { title: 'Baby Announcement', description: 'A new little one on the way.' },
  { title: 'First Steps Baby', description: 'Tiny feet taking big steps.' },
  { title: 'Toddler Tantrum', description: 'Emotions running high.' },
  { title: 'Kid Drawing', description: 'Crayon scribbles of pure joy.' },
  { title: 'Teen Hangout', description: 'Friends laughing in a bedroom.' },
  { title: 'School Lockers', description: 'Decorated metal doors.' },
  { title: 'Recess Fun', description: 'Playing on the playground.' },
  { title: 'Lunch Box', description: 'Peanut butter sandwich and juice box.' },
  { title: 'Science Fair', description: 'A project on display.' },
  { title: 'Art Class Supplies', description: 'Paints, brushes, and canvases.' },
  { title: 'Music Lesson', description: 'Learning a new instrument.' },
  { title: 'Dance Recital', description: 'Twirling in a tutu.' },
  { title: 'Sports Trophy', description: 'Shiny award for hard work.' },
  { title: 'Homecoming Court', description: 'Dresses and flowers.' },
  { title: 'Yearbook Page', description: 'Memories captured forever.' },
  { title: 'Graduation Gown', description: 'Walking across the stage.' },
  { title: 'Dorm Room', description: 'A tiny room full of personality.' },
  { title: 'College Campus', description: 'Buildings and pathways of learning.' },
  { title: 'First Salary', description: 'The excitement of earning money.' },
  { title: 'Budget Spreadsheet', description: 'Tracking income and expenses.' },
  { title: 'Savings Jar', description: 'Coins adding up over time.' },
  { title: 'Wallet Contents', description: 'Cards, cash, and receipts.' },
  { title: 'Grocery List', description: 'Weekly shopping essentials.' },
  { title: 'Meal Prep', description: 'Containers of healthy eating.' },
  { title: 'Gym Membership', description: 'New year, new fitness goals.' },
  { title: 'Running Shoes', description: 'The gear for a jogger.' },
  { title: 'Bicycle Helmet', description: 'Safety first on two wheels.' },
  { title: 'Swimming Goggles', description: 'Seeing clearly underwater.' },
  { title: 'Hiking Boots', description: 'Ready for the trail.' },
  { title: 'Camping Gear', description: 'Everything needed for outdoors.' },
  { title: 'Fishing Rod', description: 'Waiting for a nibble.' },
  { title: 'Garden Tools', description: 'Trowel, gloves, and seeds.' },
  { title: 'BBQ Grill', description: 'Sizzling food on a summer day.' },
  { title: 'Pool Floatie', description: 'Floating lazily in the pool.' },
  { title: 'Beach Umbrella', description: 'Shade on a sunny day.' },
  { title: 'Sunglasses Case', description: 'Protecting your shades.' },
  { title: 'Sun Hat', description: 'Wide brim for sun protection.' },
  { title: 'Rain Boots', description: 'Splashing in puddles.' },
  { title: 'Winter Jacket', description: 'Warmth against the cold.' },
  { title: 'Scarf and Gloves', description: 'Cold weather accessories.' },
  { title: 'Umbrella Stand', description: 'An umbrella at the ready.' },
  { title: 'Welcome Mat', description: 'A friendly greeting at the door.' },
  { title: 'Door Knocker', description: ' announcing visitors.' },
  { title: 'Wind Chime', description: 'Gentle sounds in the breeze.' },
  { title: 'Garden Hose', description: 'Watering the flowers.' },
  { title: 'Laundry Basket', description: 'Clothes waiting to be folded.' },
  { title: 'Clothesline', description: 'Drying clothes in fresh air.' },
  { title: 'Ironing Board', description: 'Getting out the wrinkles.' },
  { title: 'Sewing Machine', description: 'Creating with fabric and thread.' },
  { title: 'Tool Box', description: 'Hammers, screwdrivers, and more.' },
  { title: 'Paint Brushes', description: 'Art supplies for painting.' },
  { title: 'Pencil Collection', description: 'All the drawing tools.' },
  { title: 'Eraser Collection', description: 'Removing mistakes gently.' },
  { title: 'Sticky Notes', description: 'Reminders everywhere.' },
  { title: 'Push Pins', description: 'Holding things on the board.' },
  { title: 'Paper Clips', description: 'Organizing papers together.' },
  { title: 'Rubber Bands', description: 'All the colorful sizes.' },
  { title: 'Tape Dispenser', description: 'A roll of sticky fun.' },
  { title: 'Stapler', description: 'Putting papers together.' },
  { title: 'Hole Punch', description: 'Making holes in paper.' },
  { title: 'Scissors', description: 'Cutting things into shapes.' },
  { title: 'Ruler and Square', description: 'Measuring things precisely.' },
  { title: 'Calculator Buttons', description: 'Numbers being pressed.' },
  { title: 'Keyboard Keys', description: 'Typing away on a keyboard.' },
  { title: 'Computer Mouse', description: 'Clicking and scrolling.' },
  { title: 'Headphones On', description: 'Music filling your ears.' },
  { title: 'Microphone Stand', description: 'Ready to sing or speak.' },
  { title: 'Speaker System', description: 'Sound filling the room.' },

  // 501-600
  { title: 'Guitar Strings', description: 'Strumming a guitar.' },
  { title: 'Piano Keys', description: 'Black and white melodies.' },
  { title: 'Drum Sticks', description: 'Beating out a rhythm.' },
  { title: 'Violin Bow', description: 'Drawing music from strings.' },
  { title: 'Trumpet Shine', description: 'Brass gleaming in the light.' },
  { title: 'Flute Glint', description: 'Silver flute catching sunlight.' },
  { title: 'Harmonica Blues', description: 'Small but mighty sound.' },
  { title: 'Kazoo Buzz', description: 'Making music with a kazoo.' },
  { title: ' Tambourine Shake', description: 'Jingles shaking in rhythm.' },
  { title: 'Maracas Rhythm', description: 'Shaking up the music.' },
  { title: 'Cymbal Crash', description: 'The big hit in the song.' },
  { title: 'Triangle Ding', description: 'A simple metallic sound.' },
  { title: 'Bell Ringing', description: 'Ding dong announcing something.' },
  { title: 'Wind Chime Melody', description: 'Nature making music.' },
  { title: 'Whistling Kettle', description: 'Steam whistling from a kettle.' },
  { title: 'Clock Ticking', description: 'Time passing by.' },
  { title: 'Metronome Beat', description: 'Keeping perfect time.' },
  { title: 'Music Stand', description: 'Holding sheet music steady.' },
  { title: 'Conductor Baton', description: 'Leading the orchestra.' },
  { title: 'Sheet Music', description: 'Notes written in lines.' },
  { title: 'Record Player', description: 'Spinning vinyl sounds.' },
  { title: 'Cassette Tape', description: 'Rewinding the old days.' },
  { title: 'Radio Dial', description: 'Tuning into stations.' },
  { title: 'Speaker Cone', description: 'The part that makes sound.' },
  { title: 'Amplifier Knobs', description: 'Turning up the volume.' },
  { title: 'Mixing Board', description: 'Balancing all the sounds.' },
  { title: 'Microphone Foam', description: 'Pop filter for clear recording.' },
  { title: 'Podcast Setup', description: 'Recording a show.' },
  { title: 'YouTube Studio', description: 'Creating content at home.' },
  { title: 'Ring Light Glow', description: 'Perfect lighting for filming.' },
  { title: 'Camera Lens', description: 'Capturing the perfect shot.' },
  { title: 'Tripod Stand', description: 'Steady camera support.' },
  { title: 'Green Screen', description: 'Changing backgrounds.' },
  { title: 'Editing Timeline', description: 'Cutting clips together.' },
  { title: 'Thumbnail Sketch', description: 'Designing video previews.' },
  { title: 'Subscribe Button', description: 'Joining a channel.' },
  { title: 'Like and Comment', description: 'Interacting with content.' },
  { title: 'Live Stream', description: 'Broadcasting in real time.' },
  { title: 'VR Headset', description: 'Entering virtual worlds.' },
  { title: 'Gaming Controller', description: 'Buttons and joysticks.' },
  { title: 'Gaming Chair', description: 'Comfort during long sessions.' },
  { title: 'Streaming Setup', description: 'The ultimate streaming station.' },
  { title: 'Pixel Art', description: 'Art made of tiny squares.' },
  { title: 'ASCII Face', description: 'Text art portraits.' },
  { title: 'Emoji Party', description: 'All the emojis in one scene.' },
  { title: 'Sticker Collection', description: 'Peeling and sticking.' },
  { title: 'Temporary Tattoo', description: 'Skin art that fades.' },
  { title: 'Nail Art', description: 'Tiny paintings on nails.' },
  { title: 'Temporary Hair Color', description: 'Spray-on rainbow hair.' },
  { title: 'Jewelry Making', description: 'Beads and wires together.' },
  { title: ' friendship necklace', description: 'Two halves of a heart.' },
  { title: 'Key Chain', description: 'Keys on a decorative chain.' },
  { title: 'Luggage Tag', description: 'Identifying your bags.' },
  { title: 'Passport Pages', description: 'Stamps from travels.' },
  { title: 'Travel Sticker', description: 'Souvenirs from destinations.' },
  { title: 'Boarding Pass', description: 'Going somewhere exciting.' },
  { title: 'Hotel Key Card', description: 'Accessing the room.' },
  { title: 'Souvenir Magnet', description: 'Fridge magnets from places.' },
  { title: 'Postcard Writing', description: 'Sending words across distance.' },
  { title: 'Pen Pal Letter', description: 'Long-distance friendship.' },
  { title: 'Time Zone Clock', description: 'What time is it there?' },
  { title: 'World Map Pin', description: 'Marking visited places.' },
  { title: 'Compass Rose', description: 'Finding your direction.' },
  { title: 'Binoculars View', description: 'Zooming in on faraway things.' },
  { title: 'Magnifying Glass', description: 'Making small things big.' },
  { title: 'Microscope Slide', description: 'Tiny worlds magnified.' },
  { title: 'Telescope Peak', description: 'Looking at distant stars.' },
  { title: 'Planetarium Light', description: 'Stars projected on the ceiling.' },
  { title: 'Solar Panel Glow', description: 'Harnessing the sun.' },
  { title: 'Wind Turbine', description: 'Power from the breeze.' },
  { title: 'Water Wheel', description: 'Turning water into energy.' },
  { title: 'Dam Structure', description: 'Holding back the water.' },
  { title: 'Bridge Engineering', description: 'Spanning across gaps.' },
  { title: 'Skyscraper Top', description: 'Touching the clouds.' },
  { title: 'Construction Crane', description: 'Building tall things.' },
  { title: 'Blueprint Design', description: 'Planning before building.' },
  { title: 'Architectural Model', description: 'A tiny building replica.' },
  { title: 'Urban Planning', description: 'Designing cities.' },
  { title: 'Garden Layout', description: 'Planning planting spaces.' },
  { title: 'Landscape Design', description: 'Making outdoor spaces beautiful.' },
  { title: 'Interior Design', description: 'Making indoor spaces cozy.' },
  { title: 'Feng Shui Arrangement', description: 'Balancing energies in a room.' },
  { title: 'Minimalist Space', description: 'Less is more.' },
  { title: 'Maximalist Room', description: 'More is more fun.' },
  { title: 'Vintage Finds', description: 'Old treasures repurposed.' },
  { title: 'DIY Project', description: 'Making something yourself.' },
  { title: 'Repair Cafe', description: 'Fixing instead of replacing.' },
  { title: 'Upcycling Art', description: 'Trash becoming treasure.' },
  { title: 'Zero Waste Life', description: 'Living without waste.' },
  { title: 'Composting Bin', description: 'Food turning to soil.' },
  { title: 'Recycling Sort', description: 'Separating materials.' },
  { title: 'Ocean Cleanup', description: 'Helping the sea.' },
  { title: 'Tree Planting', description: 'One tree at a time.' },
  { title: 'Beach Cleanup', description: 'Picking up litter.' },
  { title: 'Bird Feeder', description: 'Feeding our feathered friends.' },
  { title: 'Pollinator Garden', description: 'Attracting bees and butterflies.' },
  { title: 'Rainwater Collection', description: 'Catching rain for plants.' },
  { title: 'Solar Oven', description: 'Cooking with sunlight.' },
  { title: 'Campfire Cooking', description: 'Food over flames.' },
  { title: 'Smoker BBQ', description: 'Low and slow cooking.' },
  { title: 'Stone Fire Pit', description: 'Evening warmth outside.' },
  { title: 'Garden Lights', description: 'String lights in the trees.' },
  { title: 'Tiki Torches', description: 'Tiki torch flames.' },
  { title: 'Candlelight Dinner', description: 'Romantic evening lighting.' },
  { title: ' Fairy Lights', description: 'Tiny lights everywhere.' },
  { title: 'Neon Sign', description: 'Glowing restaurant sign.' },
  { title: 'Traffic Lights', description: 'Red, yellow, green.' },
  { title: 'Billboard Art', description: 'Giant advertisements.' },
  { title: 'Street Mural', description: 'Art on city walls.' },
  { title: 'Chalk Drawing', description: 'Sidewalk art in pastels.' },
  { title: 'Spray Paint Art', description: 'Graffiti art styles.' },
  { title: 'Light Projection', description: 'Art made of light.' },
  { title: 'Shadow Puppet', description: 'Hands making animal shadows.' },
  { title: 'Mime Performance', description: 'Acting without words.' },
  { title: 'Puppet Show', description: 'Strings and characters.' },
  { title: 'Magic Trick', description: 'Appearing and disappearing.' },
  { title: 'Illusion Art', description: 'Trick your eyes.' },
  { title: '3D Drawing', description: 'Making flat paper look real.' },
  { title: 'Op Art', description: 'Movement in still images.' },
  { title: 'Abstract Feelings', description: 'Colors expressing emotions.' },
  { title: 'Geometric Pattern', description: 'Shapes fitting together.' },
  { title: ' Zentangle Doodle', description: 'Intricate tangled designs.' },
  { title: 'Mandala Circle', description: 'Radial symmetry art.' },
  { title: 'Henna Designs', description: 'Intricate temporary tattoos.' },
  { title: 'Tattoo Sketch', description: 'Designing body art.' },
  { title: 'Logo Design', description: 'Creating brand identities.' },
  { title: 'App Icon', description: 'Small but clear design.' },
  { title: 'Website Header', description: 'The top of a webpage.' },
  { title: 'Business Card', description: 'Networking with style.' },
  { title: 'Magazine Cover', description: 'Feature story layout.' },
  { title: 'Comic Strip', description: 'Panels telling a story.' },
  { title: 'Manga Panel', description: 'Japanese comic art style.' },
  { title: 'Character Design', description: 'Creating original characters.' },
  { title: 'Creature Comforts', description: 'Monsters that make you smile.' },
  { title: 'Hero and Villain', description: 'Good versus evil scene.' },
  { title: 'Sidekick Story', description: 'The loyal companion.' },
  { title: 'Quest Map', description: 'A fantasy adventure path.' },
  { title: 'Treasure Chest', description: 'Gold coins overflowing.' },
  { title: 'Magic Sword', description: 'A weapon with power.' },
  { title: 'Shield Emblem', description: 'A crest of honor.' },
  { title: 'Potion Bottles', description: 'All the magical colors.' },
  { title: 'Spell Scroll', description: 'Ancient magical writing.' },
  { title: 'Wizards Tower', description: 'A mystic place of learning.' },
  { title: 'Enchanted Library', description: 'Books that move by themselves.' },
  { title: 'Magic School', description: 'Learning to be a wizard.' },
  { title: 'Puppet Friends', description: 'Characters made of fabric.' },
  { title: 'Plushie Collection', description: 'Soft toys lined up.' },
  { title: 'Action Hero', description: 'Posable toy figure.' },
  { title: 'Dollhouse Mini', description: 'Tiny furniture and tiny lives.' },
  { title: 'Train Set', description: 'Railroads with miniature trains.' },
  { title: 'RC Car Track', description: 'Racing remote control cars.' },
  { title: 'LEGO Build', description: 'Plastic bricks becoming anything.' },
  { title: 'Puzzle Pieces', description: 'Fitting them all together.' },
  { title: 'Board Game Night', description: 'Gathering around the table.' },
  { title: 'Chess Strategy', description: 'The royal game.' },
  { title: 'Checkers Match', description: 'Jumping and capturing.' },
  { title: 'Card Game Hand', description: 'Playing cards dealt to you.' },
  { title: 'Dice Roll', description: 'Rolling the perfect number.' },
  { title: 'Domino Chain', description: 'Toppling in sequence.' },
  { title: 'Mahjong Tiles', description: 'Matching the tiles.' },
  { title: 'Jigsaw Puzzle', description: 'Seeing the whole picture.' },
  { title: 'Word Search', description: 'Finding hidden words.' },
  { title: 'Crossword Clues', description: 'Filling in the boxes.' },
  { title: 'Sudoku Grid', description: 'Number placement puzzle.' },
  { title: 'Coloring Page', description: 'Black lines waiting for color.' },
  { title: 'Dot to Dot', description: 'Connecting the numbered dots.' },
  { title: 'Maze Runner', description: 'Finding the way out.' },
  { title: 'Secret Code', description: 'Messages to decode.' },
  { title: 'Invisible Ink', description: 'Revealing hidden messages.' },
  { title: 'Love Notes', description: 'Sweet messages passed in class.' },
  { title: 'Yearbook Signing', description: 'Memories and signatures.' },
  { title: 'Memory Lane', description: 'Looking back at old photos.' },
  { title: 'Future Goals', description: 'What you want to become.' },
  { title: 'Dream Bucket List', description: 'Things to do before you die.' },
  { title: 'Life Timeline', description: 'From birth to now.' },
  { title: 'Family Tree', description: 'Roots and branches of family.' },
  { title: 'Heritage Flag', description: 'Colors of your background.' },
  { title: 'Culture Day', description: 'Celebrating where you come from.' },
  { title: 'Language Learning', description: 'New words and sounds.' },
  { title: 'Recipe Heritage', description: 'Foods from your culture.' },
  { title: 'Traditional Clothing', description: 'Cultural dress.' },
  { title: 'Holiday Traditions', description: 'Special things you do yearly.' },
  { title: 'Family Recipe', description: 'Secret ingredients passed down.' },
  { title: 'Memory Box', description: 'Treasures from the past.' },
  { title: 'Time Capsule', description: 'Messages to the future.' },
  { title: 'Legacy Letter', description: 'Words for future generations.' },
  { title: 'Gratitude Jar', description: 'Notes of thankfulness.' },
  { title: 'Kindness Chain', description: 'Pass it on activities.' },
  { title: 'Community Helpers', description: 'People who help us daily.' },
  { title: 'Essential Workers', description: 'Frontline heroes.' },
  { title: 'Healthcare Workers', description: 'Caring for the sick.' },
  { title: 'Teachers Shape', description: 'Shaping young minds.' },
  { title: 'Artists Create', description: 'Beauty from creativity.' },
  { title: 'Scientists Discover', description: 'Finding how things work.' },
  { title: 'Engineers Build', description: 'Solving problems with design.' },
  { title: 'Musicians Inspire', description: 'Healing with melodies.' },
  { title: 'Writers Tell', description: 'Stories from imagination.' },
  { title: 'Dancers Move', description: 'Expressing without words.' },
  { title: 'Photographers Capture', description: 'Freezing moments forever.' },
  { title: 'Filmmakers Dream', description: 'Creating cinematic worlds.' },
  { title: 'Architects Imagine', description: 'Buildings from imagination.' },
  { title: 'Gardeners Grow', description: 'Nurturing from seed to bloom.' },
  { title: 'Chefs Create', description: 'Edible art on plates.' },
  { title: 'Bakers Rise', description: 'Bread and pastries rising.' },
  { title: 'Cofee Brew', description: 'The morning ritual.' },
  { title: 'Tea Ceremony', description: 'Mindful tea preparation.' },
  { title: 'Smoothie Bowl', description: 'Colorful and healthy breakfast.' },
  { title: 'Acai Pack', description: 'Purple Brazilian superfood.' },
  { title: 'Avocado Toast', description: 'Simple and trendy brunch.' },
  { title: 'Matcha Latte', description: 'Green tea powdered drink.' },
  { title: 'Chai Spice', description: 'Warming chai with cinnamon.' },
  { title: 'Hot Chocolate', description: 'Rich chocolate with marshmallows.' },
  { title: 'Lemonade Fresh', description: 'Squeezed lemons and sugar.' },
  { title: 'Iced Coffee', description: 'Cold brew on a hot day.' },
  { title: 'Bubble Tea', description: 'Tea with chewy tapioca.' },
  { title: 'Mango Smoothie', description: 'Tropical fruit blend.' },
  { title: 'Green Detox', description: 'Kale and spinach juice.' },
  { title: 'Protein Shake', description: 'Post-workout fuel.' },
  { title: 'Water Bottle', description: 'Staying hydrated.' },
  { title: 'Juice Box', description: 'Convenient sweet drinks.' },
  { title: 'Soda Fizz', description: 'Bubbles and sugar.' },
  { title: 'Energy Boost', description: 'Caffeine and vitamins.' },
  { title: 'Milkshake Swirl', description: 'Ice cream blended drink.' },
  { title: 'Floats Dessert', description: 'Soda with ice cream.' },
  { title: 'Root Beer Float', description: 'Classic vanilla and soda.' },
  { title: 'Frappe Iced', description: 'Blended coffee treat.' },
  { title: 'Affogato Shot', description: 'Espresso over gelato.' },
  { title: 'Cappuccino Art', description: 'Foam art on coffee.' },
  { title: 'Drip Coffee', description: 'Slow and strong brew.' },
  { title: 'Pour Over', description: 'Careful single cup.' },
  { title: 'French Press', description: 'Full body immersion brew.' },
  { title: 'Espresso Shot', description: 'Concentrated and bold.' },
  { title: 'Cold Brew Pitcher', description: 'Steeped for hours.' },
  { title: 'Kombucha Scoby', description: 'Fermented tea culture.' },
  { title: 'Wheatgrass Shot', description: 'Energizing green juice.' },
  { title: 'Ginger Zinger', description: 'Spicy and warming.' },
  { title: 'Beetroot Red', description: 'Earthy and healthy.' },
  { title: 'Carrot Top', description: 'Orange power drink.' },
  { title: 'Cucumber Cooler', description: 'Refreshing and light.' },
  { title: 'Watermelon Wave', description: 'Summer in a glass.' },
  { title: 'Pineapple Breeze', description: 'Tropical refreshment.' },
  { title: 'Coconut Water', description: 'Natural electrolytes.' },
  { title: 'Aloe Vera Drink', description: 'Soothing and healing.' },
  { title: 'Horchata Sweet', description: 'Rice milk cinnamon drink.' },
  { title: 'Chrysanthemum Tea', description: 'Floral Chinese tea.' },
  { title: 'Jasmine Scent', description: 'Fragrant green tea.' },
  { title: 'Rose Hip Tea', description: 'Vitamin C rich brew.' },
  { title: 'Peppermint Fresh', description: 'Cool and calming.' },
  { title: 'Lavender Dreams', description: 'Relaxing floral notes.' },
  { title: 'Chamomile Calm', description: 'Sleepy time tea.' },
  { title: 'Hibiscus Tang', description: 'Tart and pretty red.' },
  { title: 'Elderflower Cordial', description: 'Sweet floral syrup.' },
  { title: 'Honey Sour', description: 'Balanced sweet and acid.' },
  { title: 'Maple Pecan Pie', description: 'Autumn dessert flavors.' },
  { title: 'Cinnamon Roll', description: 'Swirly sweet pastry.' },
  { title: 'Croissant Layers', description: 'Flaky French butter.' },
  { title: 'Danish pastry', description: 'Fruit-filled breakfast.' },
  { title: 'Eclair Cream', description: 'Long chocolate pastry.' },
  { title: 'Macaron Feet', description: 'French cookie sandwich.' },
  { title: 'Tiramisu Layers', description: 'Coffee-soaked dessert.' },
  { title: 'Panna Cotta', description: 'Wobbly Italian cream.' },
  { title: 'Tiramisu Dust', description: 'Cocoa dusting on top.' },
  { title: 'Cheesecake Base', description: 'Creamy New York style.' },
  { title: 'Brownie Fudge', description: 'Dense chocolate square.' },
  { title: 'Cookie Dough Eat', description: 'Raw but safe to eat.' },
  { title: 'Smore Marshmallow', description: 'Fire-roasted between crackers.' },
  { title: 'Banana Split', description: 'Ice cream with all the toppings.' },
  { title: 'Sunday Funday', description: 'The best dessert day.' },
]
