export const CHALLENGE_BANK = [
  { title: 'Your Morning Coffee', description: 'Draw your coffee mug, the steam rising, or what your coffee makes you feel like.' },
  { title: 'Tiny Creatures', description: 'Invent a bug, fairy, or mini monster.' },
  { title: 'Inside Your Bag', description: 'Sketch what\'s in your purse, backpack, or dream travel bag.' },
  { title: 'Rainy Day Vibes', description: 'Umbrellas, puddles, clouds, or cozy indoor scenes.' },
  { title: 'Doodle Your Mood', description: 'Use shapes, lines, or faces to express how you feel.' },
  { title: 'Magic Potions', description: 'Design bottles, labels, ingredients, and effects!' },
  { title: 'Your Favorite Snack', description: 'Sweet, salty, savory—make it cute or realistic.' },
  { title: 'Musical Shapes', description: 'What would music look like if it were a doodle?' },
  { title: 'Silly Robots', description: 'Create a funny or helpful robot with odd features.' },
  { title: 'Houseplants With Personality', description: 'Give each plant a name, face, and mood.' },
  { title: 'What\'s in the Sky?', description: 'Sun, stars, UFOs, hot air balloons—let your mind float.' },
  { title: 'Your Dream Shoes', description: 'Design sneakers, boots, or fantasy footwear.' },
  { title: 'Letters With Attitude', description: 'Make each letter of your name have its own style.' },
  { title: 'Under the Sea', description: 'Fish, coral, treasure, submarines—go deep.' },
  { title: 'The Perfect Picnic', description: 'Blankets, food, ants… or maybe a twist?' },
  { title: 'Self-Portrait as a Doodle', description: 'Draw yourself in your doodle style!' },
  { title: 'Doodle a Sound', description: 'What does laughter, wind, or traffic look like?' },
  { title: 'City in the Clouds', description: 'Floating buildings, bridges in the sky, dreamy skylines.' },
  { title: 'Your Favorite Word', description: 'Illustrate it in a creative way—with images, patterns, or color.' },
  { title: 'A Scene from Your Day', description: 'Pick a small moment and doodle it: breakfast, a walk, a nap.' },
  { title: 'Cozy Corner', description: 'Draw your favorite reading spot or relaxing place.' },
  { title: 'Breakfast Champion', description: 'Draw your favorite morning meal—pancakes, cereal, toast!' },
  { title: 'Pocket Buddy', description: 'Design a tiny creature that lives in your pocket.' },
  { title: 'Garden Friends', description: 'Draw butterflies, bees, ladybugs, or garden visitors.' },
  { title: 'My Pet (Real or Fantasy)', description: 'Draw your pet, a pet you wish you had, or a made-up creature.' },
  { title: 'Cloud Shapes', description: 'What do you see in the clouds today?' },
  { title: 'Pattern Party', description: 'Create a repeating pattern with your favorite things.' },
  { title: 'Silly Hats', description: 'Design the most ridiculous or wonderful hat you can imagine.' },
  { title: 'Food Friends', description: 'Give your favorite food a face and personality.' },
  { title: 'Window View', description: 'Draw what you see (or wish you saw) from a window.' },
  { title: 'Retro Vibes', description: 'Draw something inspired by the 70s, 80s, or 90s.' },
  { title: 'Monster Under the Bed', description: 'Design a friendly (or scary!) monster.' },
  { title: 'Transportation Dreams', description: 'Draw fantastical bikes, cars, or vehicles.' },
  { title: 'Book Cover', description: 'Design a cover for your favorite book or your life.' },
  { title: 'Meme Me', description: 'Turn yourself or your pet into a meme.' },
  { title: 'Space Explorer', description: 'Astronauts, aliens, rockets, or distant planets.' },
  { title: 'Rainbow Mood', description: 'Use rainbow colors to show your feelings.' },
  { title: 'My Hero', description: 'Draw your personal hero—real or fictional.' },
  { title: 'Tiny Kitchen', description: 'Draw a miniature kitchen with tiny cooking scenes.' },
  { title: 'Dance Move', description: 'Illustrate your favorite dance move or pose.' },
  { title: 'Weather Magic', description: 'Draw what weather would look like if it had power.' },
  { title: 'Sweet Treats', description: 'Donuts, cakes, ice cream—draw your favorites!' },
  { title: 'Dream Pet', description: 'Design an animal that doesn\'t exist in real life.' },
  { title: 'Hobby Time', description: 'Draw yourself doing your favorite hobby.' },
  { title: 'Mysterious Map', description: 'Create a map of an imaginary place.' },
  { title: 'Face Swap', description: 'Give yourself animal features or mix two faces.' },
  { title: 'Starry Night', description: 'Draw a dreamy night sky with your own constellations.' },
  { title: 'Transportation collage', description: 'Mix cars, trains, planes, and boats into one scene.' },
  { title: 'Lazy Afternoon', description: 'What do you like to do when you\'re being lazy?' },
  { title: 'Festival Fun', description: 'Draw a celebration—birthday, festival, or party scene.' },
  { title: 'Animal Kingdom', description: 'Draw animals having a meeting or party.' },
  { title: 'My Room', description: 'Sketch your bedroom or dream room.' },
  { title: 'Story Scene', description: 'Illustrate a scene from a book, movie, or your own story.' },
  { title: 'Outer Space', description: 'Planets, galaxies, astronauts, or space creatures.' },
  { title: 'Chonky Animals', description: 'Draw your favorite animals in cute, chunky style.' },
  { title: 'Flower Power', description: 'Design magical flowers with patterns and colors.' },
  { title: 'Game Character', description: 'Draw a character from your favorite game.' },
  { title: 'Morning Routine', description: 'Illustrate your typical morning step by step.' },
  { title: 'Spooky Season', description: 'Pumpkins, ghosts, or other spooky fun!' },
  { title: 'Friends Forever', description: 'Draw you and your best friend(s).' },
  { title: 'Ice Cream Truck', description: 'Design your dream ice cream truck or flavor.' },
  { title: 'Coat of Arms', description: 'Create a personal crest with your symbols.' },
  { title: 'Dinosaur World', description: 'Draw dinosaurs doing everyday human activities.' },
  { title: 'Neighborhood', description: 'Sketch your street, neighbors, or dream neighborhood.' },
  { title: 'Weather Report', description: 'Draw a weather forecast for an imaginary place.' },
  { title: 'Superpower', description: 'If you had one superpower, what would it look like?' },
  { title: 'Breakfast Around World', description: 'Draw breakfast foods from different cultures.' },
  { title: 'Cloud Home', description: 'Design a house that floats on clouds.' },
  { title: 'Music Notes', description: 'Make musical notes come alive in a doodle.' },
  { title: 'Pirate Adventure', description: 'Treasure maps, ships, or pirate crew.' },
  { title: 'Pet Day', description: 'Draw your pet doing human activities.' },
  { title: 'Time Machine', description: 'Design a vehicle that travels through time.' },
  { title: 'Silly Sandwich', description: 'Design the most absurd sandwich ever.' },
  { title: 'Jungle Safari', description: 'Lions, tigers, or exotic animals in the wild.' },
  { title: 'My Family', description: 'Draw your family as cute characters.' },
  { title: 'Dream Vacation', description: 'Where would you go? Draw it!' },
  { title: 'Magic Wand', description: 'Design a wand with specific powers.' },
  { title: 'Snow Day', description: 'Sledding, snowmen, or cozy winter scenes.' },
  { title: 'Robot Friend', description: 'Draw a friendly robot companion.' },
  { title: 'Fruit Faces', description: 'Give fruits or vegetables personalities.' },
  { title: 'Candy Land', description: 'Design a world made entirely of candy.' },
  { title: 'Talent Show', description: 'Draw someone performing their special talent.' },
  { title: 'Haunted House', description: 'Draw a spooky or funny haunted house.' },
  { title: 'Unicorn Paradise', description: 'Rainbows, glitter, and unicorn magic!' },
  { title: 'Ocean Friends', description: 'Dolphins, whales, or sea turtles having fun.' },
  { title: 'Treehouse Hideout', description: 'Design the ultimate treehouse.' },
  { title: 'Sleepy Creatures', description: 'Draw animals sleeping in funny positions.' },
  { title: 'My Hobbies', description: 'Illustrate all your hobbies in one scene.' },
  { title: 'Circus Time', description: 'Acrobats, clowns, or carnival fun!' },
  { title: 'Dragon Tales', description: 'Design a friendly dragon and its world.' },
  { title: 'Bff Bracelet', description: 'Draw friendship bracelets with symbols.' },
  { title: 'Park Adventure', description: 'Swings, slides, and playground fun.' },
  { title: 'Mushroom Village', description: 'Design a tiny village made of mushrooms.' },
  { title: 'Vacation Postcard', description: 'Create a postcard from dream vacation.' },
  { title: 'Robot Pet', description: 'Design a mechanical pet with cool features.' },
]
